In [1]:
""" ACTIVE JUPYTER NOTEBOOK TO BATCH RUN UNIT MATCHING ALGORITHM """

# To be able to make edits to repo without having to restart notebook
%load_ext autoreload
%autoreload 2


In [2]:
# Outside imports
import os, sys
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Set necessary paths / make project path = ...../neuroscikit/
unit_matcher_path = os.getcwd()
prototype_path = os.path.abspath(os.path.join(unit_matcher_path, os.pardir))
project_path = os.path.abspath(os.path.join(prototype_path, os.pardir))
lab_path = os.path.abspath(os.path.join(project_path, os.pardir))
sys.path.append(project_path)
os.chdir(project_path)
print(project_path)

# Internal imports

# Read write modules
from x_io.rw.axona.batch_read import make_study
from _prototypes.unit_matcher.read_axona import read_sequential_sessions, temp_read_cut
from _prototypes.unit_matcher.write_axona import format_new_cut_file_name

# Unit matching modules
from _prototypes.unit_matcher.main import format_cut, run_unit_matcher, map_unit_matches_first_session, map_unit_matches_sequential_session
from _prototypes.unit_matcher.session import compare_sessions
from _prototypes.unit_matcher.waveform import time_index, derivative, derivative2, morphological_points

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit


In [ ]:
""" ONLY EDIT THE SETTINGS IN THE NEXT TWO CELLS """

In [3]:
""" If a setting is not used for your analysis (e.g. smoothing_factor), just pass in an arbitrary value or pass in 'None' """
STUDY_SETTINGS = {

    'ppm': 511,  # EDIT HERE

    'smoothing_factor': 3, # EDIT HERE

    'useMatchedCut': False,  # EDIT HERE, set to False if you want to use runUnitMatcher, set to True after to load in matched.cut file
}


# Switch devices to True/False based on what is used in the acquisition (to be extended for more devices in future)
device_settings = {'axona_led_tracker': True, 'implant': True} 

# Make sure implant metadata is correct, change if not, AT THE MINIMUM leave implant_type: tetrode
implant_settings = {'implant_type': 'tetrode', 'implant_geometry': 'square', 'wire_length': 25, 'wire_length_units': 'um', 'implant_units': 'uV'}

# WE ASSUME DEVICE AND IMPLANT SETTINGS ARE CONSISTENCE ACROSS SESSIONS

# Set channel count + add device/implant settings
SESSION_SETTINGS = {
    'channel_count': 4, # EDIT HERE, default is 4, you can change to other number but code will check how many tetrode files are present and set that to channel copunt regardless
    'devices': device_settings, # EDIT HERE
    'implant': implant_settings, # EDIT HERE
}

STUDY_SETTINGS['session'] = SESSION_SETTINGS

settings_dict = STUDY_SETTINGS

In [4]:
# EDIT HERE --> change to path to your data, can ignore lab_path and put full file path to a folder as: r'path_to_data'
# data_dir = lab_path + r'\neuroscikit_test_data\20180502-ROUND-3000'
# data_dir = lab_path + r'\neuroscikit_test_data\single_sequential'
# data_dir = lab_path + r'\neuroscikit_test_data\Outputs'
# data_dir = lab_path + r'\neuroscikit_test_data\20170315-270-3525_Test' 
# data_dir = lab_path + r'\neuroscikit_test_data\RadhaData\Data\highPHF'
# data_dir = lab_path +  r'\neuroscikit_test_data\AD_group\Animal1'
# data_dir = lab_path +  r'\neuroscikit_test_data\LEC_sample_single_tet'
# data_dir = lab_path + r'\neuroscikit_test_data\20180530-ROUND-3300-1X2B3A'
# data_dir = lab_path + r'\neuroscikit_test_data\LEC_odor\Non-AD'
# data_dir = lab_path + r'\neuroscikit_test_data\LEC_odor\AD'
data_dir = lab_path + r'\neuroscikit_test_data\ANT-119a-6_20170613\ANT-119a-6_20170613'
# data_dir = lab_path + r'\neuroscikit_test_data\3_ses_folder'

# data_dir = lab_path + r'\neuroscikit_test_data\Test_File_Andrew-20221216T163437Z-001\Test_File_Andrew'


# To use in unit matching
settings_dict_unmatched = settings_dict
settings_dict_unmatched['useMatchedCut'] = False

In [ ]:
animal = study.get_animal_by_id('Odor_119a-6_tet2')
print(np.unique(animal.sessions['session_26'].get_spike_data()['spike_cluster'].cluster_labels))
print(animal.sessions['session_26'].get_cell_data()['cell_ensemble'].get_label_ids())

In [5]:
study = make_study([data_dir], settings_dict_unmatched)
study.make_animals()

SKIPPING, NO FILES FOUND FOR SESSION WITH SIGNATURE: c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\LEC_odor\AD/Odor_119a-6/All_PRISM_Sessions_iter
SKIPPING, NO FILES FOUND FOR SESSION WITH SIGNATURE: c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\LEC_odor\AD/Odor_119a-6/All_PRISM_Sessions_iter_2/PRISM_Session_ANT-119a-6_20170606-3100-odorxba_0/Tetrode
SKIPPING, NO FILES FOUND FOR SESSION WITH SIGNATURE: c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\LEC_odor\AD/sample/All_PRISM_Sessions_iter_7/PRISM_Session_ANT-119a-6_20170718-2125-odorxab_2/Tetrode
SKIPPING, NO FILES FOUND FOR SESSION WITH SIGNATURE: c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\LEC_odor\AD/Odor_119a-6/All_PRISM_Sessions_iter_4/PRISM_Session_ANT-119a-6_20170619-2375-odorxba
SKIPPING, NO FILES FOUND FOR SESSION WITH SIGNATURE: c:\Users\aaoun\OneDrive - cumc.columb

In [23]:
for animal in study.animals:
    print(animal.animal_id)
    print(animal.sessions)

B6-LEC1_20160304_tet1
{'session_1': <library.study_space.Session object at 0x000001D84C0977F0>, 'session_2': <library.study_space.Session object at 0x000001D81BE2E0B0>}
B6-LEC1_20160304_tet2
{'session_1': <library.study_space.Session object at 0x000001D84C097880>, 'session_2': <library.study_space.Session object at 0x000001D859D1AA70>}
B6-LEC1_20160304_tet3
{'session_1': <library.study_space.Session object at 0x000001D84C097DF0>, 'session_2': <library.study_space.Session object at 0x000001D859D197E0>}
B6-LEC1_20160304_tet4
{'session_1': <library.study_space.Session object at 0x000001D84C097FD0>, 'session_2': <library.study_space.Session object at 0x000001D859D1AE00>}
B6-LEC1_20160125_tet1
{'session_1': <library.study_space.Session object at 0x000001D859D1B340>, 'session_2': <library.study_space.Session object at 0x000001D84C095150>}
B6-LEC1_20160125_tet2
{'session_1': <library.study_space.Session object at 0x000001D859D189D0>, 'session_2': <library.study_space.Session object at 0x00000

In [12]:
ct = []
for animal in study.animals:
    ct.append(animal.animal_id)
print(len(ct), len(np.unique(ct)))

40 40


In [20]:
# Run unit matching on non-matched study, will save new matched cut file. 
# First all data is loaded ('Animal ID set': Animal1_tet1, Animal1_tet2, etc..)
# Then sessions PER animal and spikes per cell are sorted and  ('Session data added (to animal), spikes sorted by cell': Animal1_tet1_ses1, Animal1_tet1_ses2, etc..)
# Then unit matching begins Animal1_tet1_ses1_cell_1 vs Animal1_tet1_ses2_cell_1, Animal1_tet1_ses1_cell_1 vs Animal1_tet1_ses2_cell_2, Animal1_tet1_ses1_cell_1 vs Animal1_tet1_ses2_cell_3, etc...
unmatched_study = run_unit_matcher([data_dir], settings_dict_unmatched)
print('COMPLETED UNIT MATCHING')

Running Unit Matcher. Starting Time Tracker.
SKIPPING, NO FILES FOUND FOR SESSION WITH SIGNATURE: c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\3_ses_folder/B6-LEC1_201603
SKIPPING, NO FILES FOUND FOR SESSION WITH SIGNATURE: c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\3_ses_folder/B6-LEC1_201602
SKIPPING, NO FILES FOUND FOR SESSION WITH SIGNATURE: c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\3_ses_folder/B6-LEC1_201601
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal ID set
Animal

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160304/B6-LEC1_20160304-0_1.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160304/B6-LEC1_20160304-0.1', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160304/B6-LEC1_20160304-0.pos', 'ppm': 300.0}
339
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.43186996204507744
JSD: 0.45758464069720756
JSD: 0.40073265691102544
JSD: 0.43726080239353066
JSD: 0.4329077450029643
JSD: 0.47461198627649676
JSD: 0.4016388940835997
JSD: 0.4162633535268366
JSD: 0.41579677496219747
JSD: 0.4557139614347093
JSD: 0.41478325341155586
JSD: 0.4347926300037498
JSD: 0.4274713044175871
JSD: 0.4822353803067975
JSD: 0.40895877066888986
JSD: 0.4260887618743274
[[0.43186996 0.45758464 0.40073266 0.4372608 ]

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160304/B6-LEC1_20160304-0_2.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160304/B6-LEC1_20160304-0.2', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160304/B6-LEC1_20160304-0.pos', 'ppm': 300.0}
366
Using post PCA feature array
(5,) (4,) 97
5 4
JSD: 0.5489337120932261
JSD: 0.6598061576530191
JSD: 0.5549497239450314
JSD: 0.5678847384967858
JSD: 0.6780848578722971
JSD: 0.780097999550744
JSD: 0.6777763584483437
JSD: 0.6909730402679748
JSD: 0.4139375220667607
JSD: 0.46057222054016733
JSD: 0.44255330533278453
JSD: 0.4451656120853735
JSD: 0.5930786737476846
JSD: 0.6880601333146803
JSD: 0.5979217152200468
JSD: 0.6077803980508885
JSD: 0.44500589589382733
JSD: 0.5449808870428693
JSD:

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  indiv_ses_feats.append(np.array(indiv_cell_feats))
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\unit.py:69: RuntimeWarning: invalid value encountered in divide
  _kldiv = lambda A,

New here
[1 2 3 4 5] [1 2 3 4 5]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160304/B6-LEC1_20160304-0_3.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160304/B6-LEC1_20160304-0.3', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160304/B6-LEC1_20160304-0.pos', 'ppm': 300.0}
477
Using post PCA feature array
(5,) (5,) 97
5 5
JSD: 0.3933454188484859
JSD: 0.4110687398798177
JSD: 0.4952807939773842
JSD: 0.4854146684079871
JSD: 0.4280448902859088
JSD: 0.41524589218502356
JSD: 0.42068517277594636
JSD: 0.49526705398217574
JSD: 0.48563043217620006
JSD: 0.429973305793885
JSD: 0.39877060312063956
JSD: 0.432053026506324
JSD: 0.5081674474500506
JSD: 0.48614533713405084
JSD: 0.43769390139277575
JSD: 0.420787555731439
JSD: 0.425210597150229
JSD: 0.4974893727067365

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160304/B6-LEC1_20160304-0_4.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160304/B6-LEC1_20160304-0.4', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160304/B6-LEC1_20160304-0.pos', 'ppm': 300.0}
316
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.4011698985254666
JSD: 0.4153678694513944
JSD: 0.455911707128303
JSD: 0.41506350637087375
JSD: 0.4325324905217333
JSD: 0.4557876728193413
JSD: 0.4469658877951659
JSD: 0.43490164810962745
JSD: 0.44768880026813707
JSD: 0.4455885624996001
JSD: 0.4520813746913793
JSD: 0.46197677097979634
JSD: 0.44640793792379196
JSD: 0.4453942167749962
JSD: 0.46114425713350354
JSD: 0.43146377451340273
[[0.4011699  0.41536787 0.45591171 0.41506351]
 

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160125/B6-LEC1_20160125-90_1.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160125/B6-LEC1_20160125-90.1', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160125/B6-LEC1_20160125-90.pos', 'ppm': 300.0}
271
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.4708524432765646
JSD: 0.49483775869145324
JSD: 0.559579609279765
JSD: 0.4959062021934742
JSD: 0.5105949400652309
JSD: 0.4539400183736569
JSD: 0.5643636124664434
JSD: 0.5088218828876254
JSD: 0.6239079969695863
JSD: 0.6617210542714814
JSD: 0.5870967746741539
JSD: 0.6156379839607656
JSD: 0.5389856702918102
JSD: 0.5555340501277748
JSD: 0.5517292077533335
JSD: 0.5290056726485649
[[0.47085244 0.49483776 0.55957961 0.4959062 ]
 [0.

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  indiv_ses_feats.append(np.array(indiv_cell_feats))
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:248: VisibleDeprecationWarning: Creating an ndarray from ragged nested seque

New here
[1 2 3] [1 2 3]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160125/B6-LEC1_20160125-90_2.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160125/B6-LEC1_20160125-90.2', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160125/B6-LEC1_20160125-90.pos', 'ppm': 300.0}
30
Using post PCA feature array
(4,) (3,) 97
4 3
JSD: 0.6647886257105116
JSD: 0.6982172967597844
JSD: 0.6992300418280474
JSD: 0.848510302550577
JSD: 0.47575804248120424
JSD: 0.5560812656341282
JSD: 0.6843847496466052
JSD: 0.7252204961867582
JSD: 0.7067126783826476
JSD: 0.7098526708892906
JSD: 0.6106741972521146
JSD: 0.5981759737241926
[[0.66478863 0.6982173  0.69923004]
 [0.8485103  0.47575804 0.55608127]
 [0.68438475 0.7252205  0.70671268]
 [0.70985267 0.6106742  0.59817597]] [[[1. 1

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4 5 6] [1 2 3 4 5 6]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160125/B6-LEC1_20160125-90_3.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160125/B6-LEC1_20160125-90.3', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160125/B6-LEC1_20160125-90.pos', 'ppm': 300.0}
131
Using post PCA feature array
(4,) (6,) 97
4 6
JSD: 0.5370605304512369
JSD: 0.5560314574044112
JSD: 0.6790608952210127
JSD: 0.708720885044175
JSD: 0.6156274706105309
JSD: 0.5532676060847598
JSD: 0.705741172971075
JSD: 0.68446327329294
JSD: 0.6505998407588062
JSD: 0.6486632494386834
JSD: 0.6756076296232607
JSD: 0.8793812806641351
JSD: 0.5922931443122916
JSD: 0.5965834999675522
JSD: 0.6206783152052724
JSD: 0.6439909351593371
JSD: 0.5790977981326881
JSD: 0.7342641161093719

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160125/B6-LEC1_20160125-90_4.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160125/B6-LEC1_20160125-90.4', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160125/B6-LEC1_20160125-90.pos', 'ppm': 300.0}
60
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.6148358617608246
JSD: 0.5752257933107316
JSD: 0.5561463469568786
JSD: 0.5825486357968737
JSD: 0.6088605964977608
JSD: 0.5746123937151747
JSD: 0.5698378326717547
JSD: 0.592019860833931
JSD: 0.6639531210879775
JSD: 0.6218009070571037
JSD: 0.5039382813088544
JSD: 0.6246709874416406
JSD: 0.6529941089697038
JSD: 0.5979695850394886
JSD: 0.5368490020139031
JSD: 0.6028894509500775
[[0.61483586 0.57522579 0.55614635 0.58254864]
 [0.60

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160209/B6-LEC1_20160209-180_1.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160209/B6-LEC1_20160209-180.1', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160209/B6-LEC1_20160209-180.pos', 'ppm': 300.0}
1048
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.3926377842341973
JSD: 0.40702729022530754
JSD: 0.3943539294895498
JSD: 0.41470491769551665
JSD: 0.3948977866859148
JSD: 0.38863104427642
JSD: 0.40953895702141563
JSD: 0.38461960285534
JSD: 0.408983815272707
JSD: 0.4248132575534133
JSD: 0.3967455266545887
JSD: 0.4055876890910797
JSD: 0.4698596995111704
JSD: 0.4678437623592564
JSD: 0.44971651984444505
JSD: 0.4265501257030989
[[0.39263778 0.40702729 0.39435393 0.41470492]
 

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  indiv_ses_feats.append(np.array(indiv_cell_feats))
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\unit.py:69: RuntimeWarning: invalid value encountered in divide
  _kldiv = lambda A,

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160209/B6-LEC1_20160209-180_2.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160209/B6-LEC1_20160209-180.2', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160209/B6-LEC1_20160209-180.pos', 'ppm': 300.0}
1083
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.3693509362111851
JSD: 0.37276316291815126
JSD: 0.449592517125688
JSD: 0.39623714075256367
JSD: 0.42571518948663495
JSD: 0.379651115434081
JSD: 0.44672770245198123
JSD: 0.40531269112512247
JSD: 0.42455267384288076
JSD: 0.4497543188416917
JSD: 0.40110513127087877
JSD: 0.4430577793223518
JSD: 0.39894638774374364
JSD: 0.3995782747806664
JSD: 0.46092549622623064
JSD: 0.3789558731183674
[[0.36935094 0.37276316 0.44959252 0.396

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4 5 6 7] [1 2 3 4 5 6 7]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160209/B6-LEC1_20160209-180_3.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160209/B6-LEC1_20160209-180.3', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160209/B6-LEC1_20160209-180.pos', 'ppm': 300.0}
577
Using post PCA feature array
(5,) (7,) 97
5 7
JSD: 0.40924439817774216
JSD: 0.4081752225550779
JSD: 0.403511203989371
JSD: 0.8359784394844156
JSD: 0.8546151539299703
JSD: 0.39961348687528775
JSD: 0.7247985728530173
JSD: 0.4234556751258669
JSD: 0.38444506252435673
JSD: 0.4445924950347388
JSD: 0.86929293040372
JSD: 0.8784154703723802
JSD: 0.38874860586462867
JSD: 0.7229381229533011
JSD: 0.4406788752689072
JSD: 0.460588426953656
JSD: 0.4172472293726685
JSD: 0.80309

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160209/B6-LEC1_20160209-180_4.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160209/B6-LEC1_20160209-180.4', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160209/B6-LEC1_20160209-180.pos', 'ppm': 300.0}
1389
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.38755165414540044
JSD: 0.411997582457487
JSD: 0.39752689547175546
JSD: 0.4060335600017617
JSD: 0.37804542656887286
JSD: 0.38819901419280306
JSD: 0.3917149560287038
JSD: 0.39170353255405144
JSD: 0.37436515365915873
JSD: 0.39348792654367293
JSD: 0.3658991598028035
JSD: 0.36654104873197885
JSD: 0.4125744477184445
JSD: 0.42264979158824445
JSD: 0.4099049938445134
JSD: 0.3913063025875786
[[0.38755165 0.41199758 0.3975269  0.40

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4 5 6] [1 2 3 4 5 6]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160129/B6-LEC1_20160129-0_1.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160129/B6-LEC1_20160129-0.1', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160129/B6-LEC1_20160129-0.pos', 'ppm': 300.0}
162
Using post PCA feature array
(5,) (6,) 97
5 6
JSD: 0.5251289250299909
JSD: 0.6642522683214709
JSD: 0.509501908730396
JSD: 0.6046628861436582
JSD: 0.5268587762395559
JSD: 0.5159110379870907
JSD: 0.553461903557169
JSD: 0.6260758504776465
JSD: 0.5121406155756147
JSD: 0.5776455423661389
JSD: 0.5524776431463434
JSD: 0.5894769049120475
JSD: 0.6166376861301691
JSD: 0.6031751991043771
JSD: 0.6051942208009116
JSD: 0.5745362599775441
JSD: 0.6274523863171555
JSD: 0.7105879950450411


c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160129/B6-LEC1_20160129-0_2.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160129/B6-LEC1_20160129-0.2', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160129/B6-LEC1_20160129-0.pos', 'ppm': 300.0}
70
Using post PCA feature array
(5,) (4,) 97
5 4
JSD: 0.6001669995002099
JSD: 0.6552279904834516
JSD: 0.6141338908807638
JSD: 0.6350520289232616
JSD: 0.6247223256408851
JSD: 0.5232163999199424
JSD: 0.6201154847987462
JSD: 0.6140578259664266
JSD: 0.6096176220322899
JSD: 0.5483958668440647
JSD: 0.6080001650963627
JSD: 0.5870673564901555
JSD: 0.6108534117102602
JSD: 0.6682652601656259
JSD: 0.6007576369891767
JSD: 0.6284556844193535
JSD: 0.6238506976014627
JSD: 0.5388215293883184
JSD: 0.

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4 5] [1 2 3 4 5]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160129/B6-LEC1_20160129-0_3.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160129/B6-LEC1_20160129-0.3', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160129/B6-LEC1_20160129-0.pos', 'ppm': 300.0}
156
Using post PCA feature array
(5,) (5,) 97
5 5
JSD: 0.5235764658608876
JSD: 0.5524040264224871
JSD: 0.64634930651227
JSD: 0.59836420174131
JSD: 0.5456012135821622
JSD: 0.6262815731372834
JSD: 0.6267246878809486
JSD: 0.5991579641206319
JSD: 0.6047417496085115
JSD: 0.7010512465976031
JSD: 0.6215594362506658
JSD: 0.6057517633692975
JSD: 0.6183552819182551
JSD: 0.609031981739873
JSD: 0.6925375933649668
JSD: 0.5540637314333972
JSD: 0.568637676336545
JSD: 0.6097087121988375
JSD: 0.5

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160129/B6-LEC1_20160129-0_4.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160129/B6-LEC1_20160129-0.4', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160129/B6-LEC1_20160129-0.pos', 'ppm': 300.0}
154
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.5738535984094213
JSD: 0.5660901761008774
JSD: 0.5731809843459503
JSD: 0.5765085398996035
JSD: 0.5700461173485297
JSD: 0.5858767972925071
JSD: 0.5606477026916281
JSD: 0.5588690697247192
JSD: 0.570902061578886
JSD: 0.5775634610112838
JSD: 0.5468732141334136
JSD: 0.5695686819771719
JSD: 0.573935219206169
JSD: 0.5668117837646038
JSD: 0.5813777479140496
JSD: 0.5762310306688666
[[0.5738536  0.56609018 0.57318098 0.57650854]
 [0.57004

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  indiv_ses_feats.append(np.array(indiv_cell_feats))
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\unit.py:69: RuntimeWarning: invalid value encountered in divide
  _kldiv = lambda A,

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160216/B6-LEC1_20160216-180_1.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160216/B6-LEC1_20160216-180.1', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160216/B6-LEC1_20160216-180.pos', 'ppm': 300.0}
504
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.3768948107625666
JSD: 0.40427907881343167
JSD: 0.41128178321999026
JSD: 0.4057233877324343
JSD: 0.4113697273839603
JSD: 0.3766912464033692
JSD: 0.42052115472470064
JSD: 0.4202322767069187
JSD: 0.3999261268779052
JSD: 0.41423214352181886
JSD: 0.40732458747682493
JSD: 0.40114694115625377
JSD: 0.4085561419990711
JSD: 0.3796401454944695
JSD: 0.40742134747625736
JSD: 0.3977175617940405
[[0.37689481 0.40427908 0.41128178 0.4057

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  indiv_ses_feats.append(np.array(indiv_cell_feats))
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\unit.py:69: RuntimeWarning: invalid value encountered in divide
  _kldiv = lambda A,

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160216/B6-LEC1_20160216-180_2.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160216/B6-LEC1_20160216-180.2', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160216/B6-LEC1_20160216-180.pos', 'ppm': 300.0}
792
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.3730836860751854
JSD: 0.4143749434917185
JSD: 0.39317035719269783
JSD: 0.4168691351416791
JSD: 0.38590532585734294
JSD: 0.37745081070094444
JSD: 0.4014573099330152
JSD: 0.3833104810754572
JSD: 0.4725228810738626
JSD: 0.5206550583930066
JSD: 0.4425309108174655
JSD: 0.5224517297081804
JSD: 0.406584763326223
JSD: 0.38603238706394166
JSD: 0.4049106145784652
JSD: 0.3756171507264052
[[0.37308369 0.41437494 0.39317036 0.41686914

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  indiv_ses_feats.append(np.array(indiv_cell_feats))
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:248: VisibleDeprecationWarning: Creating an ndarray from ragged nested seque

New here
[1 2 3 4 5] [1 2 3 4 5]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160216/B6-LEC1_20160216-180_3.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160216/B6-LEC1_20160216-180.3', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160216/B6-LEC1_20160216-180.pos', 'ppm': 300.0}
167
Using post PCA feature array
(4,) (5,) 97
4 5
JSD: 0.4679158686591278
JSD: 0.6359551984388109
JSD: 0.4264501560791217
JSD: 0.4402022479142862
JSD: 0.42848308126512785
JSD: 0.49349831507847475
JSD: 0.6555983119041391
JSD: 0.4155786542605489
JSD: 0.444991280649568
JSD: 0.4407132798507353
JSD: 0.4946986007226579
JSD: 0.6094623933351452
JSD: 0.46705877161263915
JSD: 0.45378376189579916
JSD: 0.4504296673063095
JSD: 0.5095711531610214
JSD: 0.6599127129475971
JSD: 0.4431223764

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  indiv_ses_feats.append(np.array(indiv_cell_feats))
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\unit.py:69: RuntimeWarning: invalid value encountered in divide
  _kldiv = lambda A,

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160216/B6-LEC1_20160216-180_4.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160216/B6-LEC1_20160216-180.4', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160216/B6-LEC1_20160216-180.pos', 'ppm': 300.0}
522
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.40449827996847837
JSD: 0.40406878686593845
JSD: 0.4133237901540824
JSD: 0.4021816401003706
JSD: 0.41578930963208605
JSD: 0.3818612260232126
JSD: 0.4072329847792796
JSD: 0.4149626578795227
JSD: 0.4328683535159246
JSD: 0.43394498045822993
JSD: 0.4116005550528373
JSD: 0.4654218532647127
JSD: 0.39155265919547083
JSD: 0.39857512267687567
JSD: 0.3998303241602275
JSD: 0.40222018458068864
[[0.40449828 0.40406879 0.41332379 0.4021

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160308/B6-LEC1_20160308-180_1.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160308/B6-LEC1_20160308-180.1', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160308/B6-LEC1_20160308-180.pos', 'ppm': 300.0}
350
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.40300576494429013
JSD: 0.5137542807954941
JSD: 0.4829926444080493
JSD: 0.44735405455100524
JSD: 0.4289471110216561
JSD: 0.438959048372283
JSD: 0.43142676393811796
JSD: 0.42750333658205314
JSD: 0.4097524027996714
JSD: 0.49420944491371405
JSD: 0.47216903255957304
JSD: 0.4171992735247301
JSD: 0.4357280177610956
JSD: 0.4655759892025094
JSD: 0.4559941173860027
JSD: 0.3880178484387044
[[0.40300576 0.51375428 0.48299264 0.447354

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  indiv_ses_feats.append(np.array(indiv_cell_feats))
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\unit.py:69: RuntimeWarning: invalid value encountered in divide
  _kldiv = lambda A,

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160308/B6-LEC1_20160308-180_2.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160308/B6-LEC1_20160308-180.2', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160308/B6-LEC1_20160308-180.pos', 'ppm': 300.0}
787
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.38023573233653485
JSD: 0.3684425491382515
JSD: 0.4162441273039538
JSD: 0.43847449228402674
JSD: 0.37436386362164864
JSD: 0.35318977368159854
JSD: 0.39919553441601224
JSD: 0.4154515714220617
JSD: 0.4128135509766137
JSD: 0.4055311410000321
JSD: 0.3682299163878328
JSD: 0.4494687101465957
JSD: 0.5711727512583984
JSD: 0.5528988687374166
JSD: 0.5828055416081861
JSD: 0.48037738543320746
[[0.38023573 0.36844255 0.41624413 0.43847

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  indiv_ses_feats.append(np.array(indiv_cell_feats))
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:248: VisibleDeprecationWarning: Creating an ndarray from ragged nested seque

New here
[1 2 3 4 5 6] [1 2 3 4 5 6]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160308/B6-LEC1_20160308-180_3.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160308/B6-LEC1_20160308-180.3', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160308/B6-LEC1_20160308-180.pos', 'ppm': 300.0}
343
Using post PCA feature array
(5,) (6,) 97
5 6
JSD: 0.4072775375907078
JSD: 0.4268778475568591
JSD: 0.4477186758337914
JSD: 0.49960752444148
JSD: 0.4224796146717574
JSD: 0.7354986786372817
JSD: 0.4420061188583099
JSD: 0.4303999178702253
JSD: 0.4498025004643456
JSD: 0.5109757018059435
JSD: 0.4469263689862785
JSD: 0.6942059563210856
JSD: 0.4772537733457669
JSD: 0.4620154080465513
JSD: 0.45246258475883916
JSD: 0.5061517774009834
JSD: 0.49695828144714044
JSD: 0.632771510

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  indiv_ses_feats.append(np.array(indiv_cell_feats))
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\unit.py:69: RuntimeWarning: invalid value encountered in divide
  _kldiv = lambda A,

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160308/B6-LEC1_20160308-180_4.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160308/B6-LEC1_20160308-180.4', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160308/B6-LEC1_20160308-180.pos', 'ppm': 300.0}
690
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.35524289158006095
JSD: 0.3696004254020585
JSD: 0.4110652959642479
JSD: 0.3708914518878755
JSD: 0.364485993426729
JSD: 0.3519755706435924
JSD: 0.39517006558304274
JSD: 0.3783368308832148
JSD: 0.37367634285710005
JSD: 0.3928722368982466
JSD: 0.3841145160440154
JSD: 0.3897289618036183
JSD: 0.3894008361085664
JSD: 0.3859607106126955
JSD: 0.42300045223229576
JSD: 0.3869566773975675
[[0.35524289 0.36960043 0.4110653  0.37089145

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160122/B6-LEC1_20160122-0_1.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160122/B6-LEC1_20160122-0.1', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160122/B6-LEC1_20160122-0.pos', 'ppm': 300.0}
254
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.4894109782015864
JSD: 0.5090703614037161
JSD: 0.5232567872246028
JSD: 0.6413658239237423
JSD: 0.493957885155416
JSD: 0.4722295011395657
JSD: 0.5243879719142929
JSD: 0.633217916594784
JSD: 0.5282053976432494
JSD: 0.5356503818444353
JSD: 0.5123585266036589
JSD: 0.6099545334178571
JSD: 0.5327175216556723
JSD: 0.5208768482442052
JSD: 0.5408510944371153
JSD: 0.601328216109907
[[0.48941098 0.50907036 0.52325679 0.64136582]
 [0.493957

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  indiv_ses_feats.append(np.array(indiv_cell_feats))
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\unit.py:69: RuntimeWarning: invalid value encountered in divide
  _kldiv = lambda A, B: np.sum([v for v in A * np.log(A/B) if not np.isnan(v).any()])
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\unit.py:69: RuntimeWarning: divide by zero encountered in log
  _kldiv = lambda A, B: np.sum([v for v in A * np.log(A/B) if not np.isnan(v).any()])
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neu

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160122/B6-LEC1_20160122-0_2.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160122/B6-LEC1_20160122-0.2', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160122/B6-LEC1_20160122-0.pos', 'ppm': 300.0}
54
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.6153656000708716
JSD: 0.6625215500538979
JSD: 0.6372746562453436
JSD: 0.6108703026767915
JSD: 0.61756747760612
JSD: 0.5775304863986737
JSD: 0.6441620950677468
JSD: 0.6118521298755645
JSD: 0.6447422992397486
JSD: 0.6837575095090821
JSD: 0.6336185525332726
JSD: 0.6545680128737422
JSD: 0.6244867455273523
JSD: 0.5662087916602662
JSD: 0.6567661330462219
JSD: 0.6083051942448284
[[0.6153656  0.66252155 0.63727466 0.6108703 ]
 [0.617567

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4 5] [1 2 3 4 5]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160122/B6-LEC1_20160122-0_3.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160122/B6-LEC1_20160122-0.3', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160122/B6-LEC1_20160122-0.pos', 'ppm': 300.0}
87
Using post PCA feature array
(4,) (5,) 97
4 5
JSD: 0.5709582844031853
JSD: 0.591318988245481
JSD: 0.5282215585309749
JSD: 0.5603548886389771
JSD: 0.569037565327815
JSD: 0.577533734225095
JSD: 0.5986129310096855
JSD: 0.5036908182187652
JSD: 0.5324586605809781
JSD: 0.5603050609728322
JSD: 0.5862100576984571
JSD: 0.5942027295452088
JSD: 0.5332766026134564
JSD: 0.5452803470124122
JSD: 0.5576246128323028
JSD: 0.6240710704073112
JSD: 0.6372652289009346
JSD: 0.5478552453516299
JSD: 0

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160122/B6-LEC1_20160122-0_4.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160122/B6-LEC1_20160122-0.4', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160122/B6-LEC1_20160122-0.pos', 'ppm': 300.0}
76
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.6273632718186519
JSD: 0.6405904172587673
JSD: 0.7196407107164777
JSD: 0.6443629477867854
JSD: 0.6618044113052517
JSD: 0.6523061495802289
JSD: 0.7562681114052789
JSD: 0.6666258360568694
JSD: 0.6273475981180017
JSD: 0.7261154875455248
JSD: 0.5060405001301105
JSD: 0.6019439400100909
JSD: 0.6023784672026823
JSD: 0.691814996551482
JSD: 0.5491931436677074
JSD: 0.5834807813837365
[[0.62736327 0.64059042 0.71964071 0.64436295]
 [0.66180

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160208/B6-LEC1_20160208-90_1.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160208/B6-LEC1_20160208-90.1', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160208/B6-LEC1_20160208-90.pos', 'ppm': 300.0}
737
Using post PCA feature array
(6,) (4,) 97
6 4
JSD: 0.5521157251588825
JSD: 0.5628458295042365
JSD: 0.5282582381834036
JSD: 0.5695343189596745
JSD: 0.5323661838202469
JSD: 0.5239277090192163
JSD: 0.4929655581006629
JSD: 0.5323670740992189
JSD: 0.4814887346635469
JSD: 0.4687722715949803
JSD: 0.4381317310047349
JSD: 0.4646970644062158
JSD: 0.5545334249680831
JSD: 0.5491231515727159
JSD: 0.5268160709681069
JSD: 0.5742178624794565
JSD: 0.4590212956140387
JSD: 0.4705444363133671
JSD

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160208/B6-LEC1_20160208-90_2.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160208/B6-LEC1_20160208-90.2', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160208/B6-LEC1_20160208-90.pos', 'ppm': 300.0}
1194
Using post PCA feature array
(5,) (4,) 97
5 4
JSD: 0.3927526690902118
JSD: 0.3918076318108104
JSD: 0.4479866935687419
JSD: 0.3922938043825653
JSD: 0.5156427823055074
JSD: 0.4712844383800521
JSD: 0.4991425482195973
JSD: 0.4931319863892372
JSD: 0.5151962341204465
JSD: 0.5158933035339194
JSD: 0.5508684909064389
JSD: 0.5268976351391164
JSD: 0.5003221053744344
JSD: 0.49494669019035553
JSD: 0.5002007594039835
JSD: 0.49028500445805345
JSD: 0.41959825205326373
JSD: 0.3895427465221177

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160208/B6-LEC1_20160208-90_4.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160208/B6-LEC1_20160208-90.4', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160208/B6-LEC1_20160208-90.pos', 'ppm': 300.0}
1205
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.3700647268523207
JSD: 0.4402389307631387
JSD: 0.37071291026403663
JSD: 0.4253057411872292
JSD: 0.37369285305509903
JSD: 0.4237092950972287
JSD: 0.3756718050841235
JSD: 0.4390806296327701
JSD: 0.3892656716800796
JSD: 0.43361764891241406
JSD: 0.36118045405890725
JSD: 0.4380173886844721
JSD: 0.39832129735959737
JSD: 0.44573791649052363
JSD: 0.3935383476744072
JSD: 0.4226214906378771
[[0.37006473 0.44023893 0.37071291 0.4253057

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160128/B6-LEC1_20160128-0_1.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160128/B6-LEC1_20160128-0.1', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160128/B6-LEC1_20160128-0.pos', 'ppm': 300.0}
180
Using post PCA feature array
(5,) (4,) 97
5 4
JSD: 0.5323506320373993
JSD: 0.4988238206016634
JSD: 0.5388955614528399
JSD: 0.5325287342394913
JSD: 0.6783416018908704
JSD: 0.7079091395077524
JSD: 0.7038817823545568
JSD: 0.793304250906889
JSD: 0.5496915639030873
JSD: 0.5100197235146321
JSD: 0.545099556088208
JSD: 0.5788282445923062
JSD: 0.5721390138701149
JSD: 0.5872244727345401
JSD: 0.552969873963109
JSD: 0.608155610855915
JSD: 0.5645189791157339
JSD: 0.5799120332973171
JSD: 0.558

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  indiv_ses_feats.append(np.array(indiv_cell_feats))
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:248: VisibleDeprecationWarning: Creating an ndarray from ragged nested seque

New here
[1 2 3] [1 2 3]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160128/B6-LEC1_20160128-0_2.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160128/B6-LEC1_20160128-0.2', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160128/B6-LEC1_20160128-0.pos', 'ppm': 300.0}
275
Using post PCA feature array
(4,) (3,) 97
4 3
JSD: 0.7587663526744399
JSD: 0.6545243940293864
JSD: 0.7175814547585762
JSD: 0.5347123317358353
JSD: 0.7420988618106519
JSD: 0.5583186618221979
JSD: 0.8188946762477551
JSD: 0.6761767424348754
JSD: 0.7580170191794171
JSD: 0.6618760565259195
JSD: 0.667254391748306
JSD: 0.6105013092743161
[[0.75876635 0.65452439 0.71758145]
 [0.53471233 0.74209886 0.55831866]
 [0.81889468 0.67617674 0.75801702]
 [0.66187606 0.66725439 0.61050131]] [[[1. 1.]


c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4 5] [1 2 3 4 5]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160128/B6-LEC1_20160128-0_3.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160128/B6-LEC1_20160128-0.3', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160128/B6-LEC1_20160128-0.pos', 'ppm': 300.0}
161
Using post PCA feature array
(4,) (5,) 97
4 5
JSD: 0.5522820030110639
JSD: 0.6534903201432541
JSD: 0.6360895847206769
JSD: 0.5513381580050547
JSD: 0.5712432659761626
JSD: 0.612934540528279
JSD: 0.6233274312365406
JSD: 0.6149761646524431
JSD: 0.6315504443620683
JSD: 0.6698058473028256
JSD: 0.5638063005463317
JSD: 0.6553773447283671
JSD: 0.6379407632634003
JSD: 0.5455972143380957
JSD: 0.5856072171209757
JSD: 0.5509142817039334
JSD: 0.7293232624944773
JSD: 0.7158739894308266
JSD

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  indiv_ses_feats.append(np.array(indiv_cell_feats))
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\unit.py:69: RuntimeWarning: invalid value encountered in divide
  _kldiv = lambda A,

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160128/B6-LEC1_20160128-0_4.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160128/B6-LEC1_20160128-0.4', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160128/B6-LEC1_20160128-0.pos', 'ppm': 300.0}
105
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.5804500060825388
JSD: 0.5807693318659952
JSD: 0.6341102280274238
JSD: 0.6485379993393896
JSD: 0.6358310182733286
JSD: 0.6376545230001349
JSD: 0.7093994412697807
JSD: 0.726545177874834
JSD: 0.5702305797579788
JSD: 0.5845836786287795
JSD: 0.5519270350786843
JSD: 0.5725151433727473
JSD: 0.5745224038946267
JSD: 0.5789755343959255
JSD: 0.6221072304119941
JSD: 0.6291886453165234
[[0.58045001 0.58076933 0.63411023 0.648538  ]
 [0.6358

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160212/B6-LEC1_20160212-0_1.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160212/B6-LEC1_20160212-0.1', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160212/B6-LEC1_20160212-0.pos', 'ppm': 300.0}
497
Using post PCA feature array
(5,) (4,) 97
5 4
JSD: 0.40025193026597444
JSD: 0.43962960192375977
JSD: 0.47040027543750396
JSD: 0.4355684254253985
JSD: 0.44358317056747976
JSD: 0.43897098215705205
JSD: 0.4584423572475048
JSD: 0.4471990176878099
JSD: 0.7551754759161353
JSD: 0.7070639960908875
JSD: 0.709379390560098
JSD: 0.7030647674167235
JSD: 0.4074250632234651
JSD: 0.47108773951990224
JSD: 0.44472526319722777
JSD: 0.4734949207579088
JSD: 0.46893492312247226
JSD: 0.4710223559871671

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160212/B6-LEC1_20160212-0_2.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160212/B6-LEC1_20160212-0.2', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160212/B6-LEC1_20160212-0.pos', 'ppm': 300.0}
900
Using post PCA feature array
(4,) (4,) 97
4 4
JSD: 0.3741452952221207
JSD: 0.39951286661779717
JSD: 0.475777114151254
JSD: 0.42033642117247316
JSD: 0.4083555938731529
JSD: 0.39629008285513534
JSD: 0.47862108518805374
JSD: 0.3984050986334911
JSD: 0.45357667502447896
JSD: 0.44868699837133896
JSD: 0.4545121917952457
JSD: 0.47586557528658624
JSD: 0.4023369743196033
JSD: 0.4127613737023977
JSD: 0.49488814516123764
JSD: 0.3889915948271662
[[0.3741453  0.39951287 0.47577711 0.42033642]


c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4] [1 2 3 4]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160212/B6-LEC1_20160212-0_3.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160212/B6-LEC1_20160212-0.3', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160212/B6-LEC1_20160212-0.pos', 'ppm': 300.0}
511
Using post PCA feature array
(5,) (4,) 97
5 4
JSD: 0.4034877374677746
JSD: 0.4605392492061244
JSD: 0.4634689572967376
JSD: 0.44834354618837285
JSD: 0.4403603759034635
JSD: 0.40664047807185266
JSD: 0.4692483847006229
JSD: 0.46305667457388167
JSD: 0.4129172329886717
JSD: 0.46302041286428464
JSD: 0.44035802928079376
JSD: 0.45088105595108147
JSD: 0.6594715676256667
JSD: 0.6527246999638702
JSD: 0.625200985917529
JSD: 0.6310571809368276
JSD: 0.4393308319266785
JSD: 0.4633500349267548
J

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray fro

New here
[1 2 3 4 5] [1 2 3 4 5]
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160212/B6-LEC1_20160212-0_4.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160212/B6-LEC1_20160212-0.4', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\3_ses_folder/B6-LEC1_20160212/B6-LEC1_20160212-0.pos', 'ppm': 300.0}
487
Using post PCA feature array
(4,) (5,) 97
4 5
JSD: 0.4285825145890856
JSD: 0.42324423913914
JSD: 0.5608664354440026
JSD: 0.8108037559360582
JSD: 0.5191379979410604
JSD: 0.4408233196195572
JSD: 0.4439641365029499
JSD: 0.496622027771838
JSD: 0.7154669646217814
JSD: 0.4542715857952991
JSD: 0.49006954447846707
JSD: 0.47808442643495447
JSD: 0.45262333550868306
JSD: 0.7291812287689995
JSD: 0.4659486752366459
JSD: 0.5281108711605639
JSD: 0.5424819346572145
JSD: 0.49282427485648084
J

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:321: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**4) / (n * std**4)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\waveform.py:302: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum((data - mean)**3) / (n * std**3)
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit\_prototypes\unit_matcher\main.py:246: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  indiv_ses_feats.append(np.array(indiv_cell_feats))


UnboundLocalError: local variable 'comparison' referenced before assignment

In [ ]:
# Quick check that session file are grouped correctly + ordered in time
tets = []
for ses in unmatched_study.animals[0].sessions:
    print(unmatched_study.animals[0].sessions[ses].session_metadata.file_paths)
    tets.append(unmatched_study.animals[0].sessions[ses].session_metadata.file_paths['tet'])
    print(unmatched_study.animals[0].sessions[ses].datetime)

In [ ]:
sorted(tets)

In [ ]:
# New settings dictionary indicating the matched cut file should now be used for file loading
settings_dict_matched = settings_dict
settings_dict_matched['useMatchedCut'] = True

# Load new study but using labels from matched cut file
matched_study = make_study([data_dir], settings_dict_matched)

# Sort spikes by cell and order sessions sequentially
matched_study.make_animals()

In [ ]:
# Look at matched cell ids from new cut files
for animal in matched_study.animals:
    print('New Animal')
    for session in animal.sessions.values():
        print('Session date & time: ' + str(session.datetime))
        print('Matched cell ids: ' + str(np.unique(session.get_spike_data()['spike_cluster'].cluster_labels)))

In [ ]:
# Pull out session classes and cell ensembles from matched and unmatched studies for plotting

session1 = matched_study.animals[0].sessions['session_1']
ensemble1 = matched_study.animals[0].ensembles['session_1']
session2 = matched_study.animals[0].sessions['session_2']
ensemble2 = matched_study.animals[0].ensembles['session_2']

unmatched_ensembles1 = unmatched_study.animals[0].ensembles['session_1']
unmatched_ensembles2 = unmatched_study.animals[0].ensembles['session_2']

In [ ]:
""" Plot session 1 (left) & session 2 (right) MATCHED units """

pair_count = len(ensemble1.get_label_ids())

for i in range(pair_count):
# for i in range(2):

    fig = plt.figure(figsize=(6,12))

    axes = []

    waveforms1 = ensemble1.cells[i].signal
    waveforms2 = ensemble2.cells[i].signal

    avg_waveforms1 = np.mean(waveforms1, axis=0)
    avg_waveforms2 = np.mean(waveforms2, axis=0)

    assert waveforms1.shape[1] == avg_waveforms1.shape[0]

    for j in range(0,avg_waveforms1.shape[0]*2,2):
        ax1 = plt.subplot(avg_waveforms1.shape[0],2,j+1)
        ax2 = plt.subplot(avg_waveforms1.shape[0],2,j+2)

        ax1.plot(waveforms1[:,int(j/2)].T, color='gray', lw=0.5, alpha=0.5)
        ax2.plot(waveforms2[:,int(j/2)].T, color='gray', lw=0.5, alpha=0.5)

        ax1.plot(avg_waveforms1[int(j/2)], color='k', lw=2)
        ax2.plot(avg_waveforms2[int(j/2)], color='k', lw=2)

        ax1.set_title('Channel ' + str(int(j/2+1)))
        ax2.set_title('Channel ' + str(int(j/2+1)))

        axes.append(ax1)
        axes.append(ax2)

    for ax in axes:
        ax.set_xlabel('Bin Number')
        ax.set_ylabel('Waveform')

    fig.suptitle('Session 1 (left) & 2 (right) - Unit ' + str(i+1))

    fig.tight_layout()
    plt.show()
